@section('page','Terms and Conditions - ')

@extends('layouts.services')
@section('main-content')
<!-- Banner -->
<section id="slider" class="p-0 featured odd"
    style="background:linear-gradient(45deg,#00000012,#000000c4),url(/assets/images/banners/services.jpg)">
    <div class="swiper-container slider-disabled slider-h-75">
        <div class="swiper-wrapper">

            <!-- Item 1 -->
            <div class="swiper-slide slide-center">
                <!-- 
                        Custom Image
                        <img src="/assets/images/bg-1.jpg" class="image-fit banner">
                    -->
                <div class="slide-content row text-center">
                    <div class="col-12 mx-auto inner">
                        <h1 data-aos="zoom-out-up" data-aos-delay="400" class="title effect-static-text">Terms and
                            Conditions

                        </h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section id="intro">
    <div class="container mt-90">
        <div class="row mt-90">

            <div class="col-sm-12  mt-90">
                <p class="text-justify"><strong>PLEASE READ THESE TERMS AND CONDITIONS OF USE AGREEMENT (&ldquo;Agreement&rdquo;) CAREFULLY. BY ACCESSING OR UTILIZING THE SERVICES THROUGH THE WEBSITE, YOU CONSENT TO BE BOUND BY THE TERMS AND CONDITIONS OF THIS AGREEMENT AND PRIVACY POLICY. IF YOU DO NOT WISH TO BE BOUND BY THIS AGREEMENT, KINDLY DO NOT ACCESS/USE THE WEBSITE.</strong></p>

<p class="text-justify"><strong>This document is an electronic record in terms of the Information Technology Act, 2000 and the rules thereunder as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</strong></p>

<p class="text-justify">These terms and conditions relate to: [www.nyxwolves.com] (&ldquo;<strong>Website&rdquo;/ &ldquo;Nyx Wolves&rdquo;/ &ldquo;We</strong>&rdquo;). Nyx Wolves is <em>inter alia </em>in the business of creating branding &amp; identity for businesses, web design &amp; development, AI &amp; digital platforms and digital marketing. Any mention of Website or in these terms and conditions shall automatically be understood as referring also to the Website or the of Nyx Wolves, as the context may require.</p>

<p class="text-justify">This Agreement between the User (&ldquo;<strong>You</strong>&rdquo;) and&nbsp;<strong>Nyx Wolves </strong>elucidates the broad terms &amp; conditions governing Your use of the products and services available on the Website. You must apprise Yourself with these terms as they describe Your privileges &amp; rights as a subscriber. We recognize that the confidentiality and safety of Your personal records are essential and we utilize the most innovative security technology existing to guard Your confidentiality. These terms and conditions may be modified/updated by us from time to time. By continuing to use our Website, You agree to such modified/updated terms and conditions as provided by us on our Website. If You do not agree to any of these terms, You are prohibited from using or accessing this Website.</p>

<p class="text-justify"><strong>About us</strong></p>

<p class="text-justify">The Website are owned and provided by&nbsp;<strong>Nyx Wolves</strong>. If You need any information or have a complaint about this Website or any of our services, please write to us at: <strong>  howl@nyxwolves.com </strong>. You may also contact us at +91<strong>  63817  51802</strong>.</p>


<p class="text-justify"><strong>Privacy</strong></p>

<ul>
	<li>
	<p class="text-justify">Your privacy and the privacy of any other person whose information You provide important to us. Please see our privacy policy for details of what information we collect and how we will use and protect it.</p>
	</li>
	<li>
	<p class="text-justify">You are responsible for keeping Your device(s) safe and for ensuring that it is not used by any other person.</p>
	</li>
	<li>
	<p class="text-justify">By using this Website, You confirm that the information You provide during the use process is accurate and complete. You agree to update any and all of Your details, if there are any changes, at the earliest. All information You provide will be kept secure and processed in accordance with our privacy policy and other applicable laws.</p>
	</li>
</ul>

<ul>
	<li>
	<p class="text-justify">Nyx Wolves may use cache to store certain data which is not sensitive personal information or data that is used for technical administration of the Website, research and development and for User administration. In the course of providing the User optimal services, Nyx Wolves may permit authorized third parties to place advertisements of their goods and services and clicking on such advertisements may redirect You to the third party&rsquo;s website. Nyx Wolves is in no way responsible for the acts of such third parties.</p>
	</li>
	<li>
	<p class="text-justify">Nyx Wolves can also initiate SMS and emails to the customer regarding offers and newsletters. However, the customer can always opt out of the communication by mailing us at&nbsp;<strong>howl@nyxwolves.com</strong>. Unless You specifically opt out, You agree to receive SMS and email updates/offers as detailed above. You may also contact us at +91<strong>  6381757802</strong>.</p>
	</li>
</ul>

<p class="text-justify"><strong>Definitions</strong></p>

<ul>
	<li>
	<p class="text-justify">&ldquo;<strong>We</strong>&rdquo; shall mean the Website and Nyx Wolves.</p>
	</li>
	<li>
	<p class="text-justify">&ldquo;<strong>Website</strong>&rdquo; shall mean [www.nyxwolves.com] and shall include the mobile phone owned by Nyx Wolves called www.nyxwolves.com  .</p>
	</li>
	<li>
	<p class="text-justify">&ldquo;<strong>User/ You</strong>&rdquo; shall mean an individual accessing from the Website.</p>
	</li>
</ul>





<p class="text-justify"><strong>Terms and conditions for all services</strong></p>

<p class="text-justify">Nyx Wolves shall provide You and You shall acquire from Nyx Wolves the services set forth in the Nyx Wolves quote or order form (&ldquo;Quote or Order Form&rdquo;) under which You purchased those services and as specified in more detail in the services schedule (if any) attached to that Quote or Order Form (&quot;Consulting Services&quot;). Nyx Wolves shall provide the Consulting Services at the location (if any) set out on the Quote or Order Form in accordance with the timetable set forth in the Services Schedule (if any). Nyx Wolves may subcontract all or any portion of performance of the Consulting Services to one or more authorized third party(ies) under the direction of Nyx Wolves provided that Nyx Wolves shall at all times remain responsible for the performance of the Consulting Services. You are bound by the Website Terms and Conditions and Privacy Policy for any and all services obtained by You.</p>

<p class="text-justify"><strong>Methods of Electronic Communication</strong></p>

<p class="text-justify">As You visit our Website or send any emails to use, You actually are communicating electronically. With this communication You give the consent for receiving communication from our end electronically. We can post notices to our Website or communicate with Your directly through mail. You agree that all the notices and any other forms of communications that are provided by us electronically completely satisfy any kinds of legal necessities and such communications are in writing terms.</p>

<p class="text-justify"><strong>Prices</strong></p>

<p class="text-justify">The prices that we may post in the Website can be changed without any prior notice. The prices that are available before the commencement of order will be applicable. The prices that are posted, if any, also include charges and taxes. In case, if there are any additional charges, it will be notified on the Website.</p>

<p class="text-justify"><strong>Conditions of Payment</strong></p>

<p class="text-justify">Nyx Wolves will invoice fees, actual expenses and taxes, if any, monthly and at project completion. Payment is in accordance with Quote or Order Form terms and Website terms. Customer shall reimburse Nyx Wolves for all materials, applicable taxes, and all reasonable out-of-pocket expenses incurred by Nyx Wolves in providing the services including, without limitation, project-related travel and living expenses. Save in the case of pre-approved expenses, Nyx Wolves shall obtain YOUR prior approval for any travel or travel related expenses. Customer will include a line item for such expenses on its purchase order or purchase order exception document.</p>

<p class="text-justify"><strong>License to Work Products</strong></p>

<p class="text-justify"><strong>Nyx Wolves grants You a perpetual, worldwide, non-exclusive, non-transferable, royalty-free license to use the Consulting Services and the products, concepts, materials, techniques, methods and know-how included in or with the Consulting Services in Customer&rsquo;s internal business operations. This license shall not apply to any Nyx Wolves or third-party software which may be provided prior to, concurrent with or following the provision of the Consulting Services. Customer&rsquo;s use of such software shall be governed exclusively by the license agreement(s) accompanying such software.</strong></p>

<p class="text-justify"><strong>Cancellation charges</strong></p>

<p class="text-justify"><strong>In the event that the Consulting Services has been delivered in its entirety, You will not cancel the Order. In the event of such cancellation, You agree to pay the entire fee as per the Order Form. In the event of cancellation for any reason for work in progress, You shall pay Nyx Wolves for all Consulting Services and deliverables (where applicable) provided up to the date of cancellation at an amount equivalent to that proportion of the Consulting Services provided to the date of cancellation, as well as for all work-in process on a time and materials basis at the then current standard Nyx Wolves rates for similar services. In the event of cancellation as aforesaid by Nyx Wolves, You shall also reimburse Nyx Wolves for all costs incurred or renegotiate any supplier or sub-contract agreements that Nyx Wolves entered into in connection with this service agreement or for redeployment of Nyx Wolves personnel.</strong></p>

<p class="text-justify"><strong>About Your Account:</strong></p>

<p class="text-justify"><strong>Protection:</strong>&nbsp;As per the privacy policy of the Website You are responsible for maintaining the confidentiality of the account and password You have, so that You can restrict access to Your computer. In addition to that You also accept the responsibility of all the activities that occur under Your User account.</p>

<p class="text-justify"><br />
<strong>Children:</strong>&nbsp;If You are under the age of 18, You can use the site with the involvement of a parent and guardian. The site also reserves the right to refuse the service or terminate the account or removing the content of the edit.</p>



<p class="text-justify"><strong>Wrong information</strong></p>

<p class="text-justify">You represent that the information provided by You only relates to You and not to any third party. Usage of false information or misrepresenting to be a third person/impersonation shall result in us removing all of Your content and at our sole discretion We may choose to not provide services/products to You through our Website.</p>



<p class="text-justify"><strong>Indemnification</strong></p>

<p class="text-justify">The User agrees to indemnify, defend and hold harmless Nyx Wolves from and against any and all losses, liabilities, claims, damages, costs and expenses (including legal fees and disbursements in connection therewith and interest chargeable thereon) asserted against or incurred by Nyx Wolves that arise out of, result from, or may be payable by virtue of, any breach or non-performance of any representation, warranty, covenant or agreement made or obligation to be performed by the User pursuant to this Agreement .</p>



<p class="text-justify"><strong>Limited user</strong></p>

<p class="text-justify">The User agrees and undertakes not to sell, trade or resell or exploit for any commercial purposes, any portion of the products or services, without Nyx Wolves&rsquo; prior written consent.</p>



<p class="text-justify">The User further agrees and undertakes not to reverse engineer, modify, copy, distribute, transmit, display, perform, reproduce, publish, license, create derivative works from, transfer, or sell any information, software, products or services obtained from the Website. For the removal of doubt, it is clarified that unlimited or wholesale reproduction, copying of the content for commercial or non-commercial purposes and unwarranted modification of data and information within the content of the Website is not permitted.</p>





<p class="text-justify"><strong>Termination/Access restriction</strong></p>

<p class="text-justify">Nyx Wolves reserves the right, in its sole discretion, to terminate the access to the Website and the related services or any portion thereof at any time, without notice.</p>



<p class="text-justify"><strong>Relationship</strong></p>

<p class="text-justify">None of the provisions of this Agreement, terms and conditions, notices or the right to use the Website by the User contained herein or any other section or pages of the Website and/or the linked sites, shall be deemed to constitute a partnership between the User and Nyx Wolves and no party shall have any authority to bind or shall be deemed to be the agent of the other in any way.</p>



<p class="text-justify"><strong>Rights of Intellectual Property</strong></p>

<p class="text-justify"><strong>Copyright:</strong>&nbsp;All the contents like graphics, texts, button icons, logos, digital downloads, audio clips is the property of Nyx Wolves and is completely protected by Indian law of Copyright. The content is also the exclusive property of Nyx Wolves. However, the same is subject to the Licence to Work Products.</p>

<p class="text-justify"><strong>Trademarks:</strong></p>

<p class="text-justify"><strong>Protected Marks:</strong>&nbsp;The protected marks include (Website) &amp; design and other things that are in the Website.</p>

<p class="text-justify"><strong>Protected Graphics:</strong>&nbsp;The graphics, page headers, logos, icons, scripts are trademarks of the site. These trademarks and trade dress might not be used in relation to products and services that are not of Nyx Wolves. All the other trademarks are owned by the Nyx Wolves and its affiliate sites. These are the property of different owners. They might not be connected to or affiliated with Nyx Wolves.</p>

<p class="text-justify">All other intellectual property (as defined by applicable laws) relating to the products/services and other content available on the Website shall be the sole property of Nyx Wolves and may not be used by the User without prior written consent of Nyx Wolves.</p>

<p class="text-justify"><strong>Disclaimer</strong></p>

<p class="text-justify">NYX WOLVES DOES NOT WARRANT OR REPRESENT THAT THE MATERIAL ON THIS WEBSITE IS ACCURATE, COMPLETE OR CURRENT OR THAT THE WEBSITE WILL BE FREE OF DEFECTS OR VIRUSES THOUGH DUE CARE IS CONSTANTLY TAKEN ON THE PART OF NYX WOLVES. NOTHING CONTAINED IN THE PAGES OF THIS WEBSITE SHOULD BE CONSTRUED AS LEGAL, MEDICAL, COMMERCIAL, OR OTHER PROFESSIONAL ADVICE. DETAILED PROFESSIONAL ADVICE SHOULD BE OBTAINED BEFORE TAKING OR REFRAINING FROM ANY ACTION BASED ON ANY OF THE INFORMATION OR MATERIAL CONTAINED IN THIS WEBSITE OR ANY COMMUNICATIONS PROVIDED TO YOU AS A RESULT OF YOUR REGISTRATION. IT IS YOU AS A CUSTOMER WHO AGREES THAT THE USE OF THIS SITE IS SOLELY AT YOUR OWN RISK.</p>



<p class="text-justify"><strong>Limitation of Liability</strong></p>

<p class="text-justify">WE WILL NOT BE LIABLE FOR ANY LOSS OR DAMAGE (IN CONTRACT, NEGLIGENCE OR OTHERWISE) WHERE:</p>

<ul>
	<li>
	<p class="text-justify">THERE IS NO BREACH OF A LEGAL DUTY OF CARE OWED TO YOU BY US;</p>
	</li>
	<li>
	<p class="text-justify">THE LOSS OR DAMAGE IS NOT A REASONABLY FORESEEABLE RESULT OF ANY SUCH BREACH; OR</p>
	</li>
	<li>
	<p class="text-justify">ANY LOSS OR DAMAGE OR INCREASE IN LOSS OR DAMAGE RESULTS FROM A BREACH BY YOU OF THESE TERMS AND CONDITIONS.THE MAXIMUM LIABILITY SHALL BE LIMITED TO THE COST OF THE PRODUCTS PURCHASED OR SERVICES AVAILED BY THE CUSTOMER, NYX WOLVES SHALL NOT BE LIABLE FOR ANY INDIRECT, CONSEQUENTIAL OR OTHER DAMAGES CAUSED TO THE USER.</p>
	</li>
</ul>

<p class="text-justify">WE ADDITIONALLY WILL NOT BE LIABLE IN CASE THE USER OF THE WEBSITE HAS MISREPRESENTED ANY OF THE INFORMATION PROVIDED BY THEM DURING THE USE PROCESS OR OTHERWISE. ANY AND ALL SERVICES PROVIDED BY US SHALL BE UNINTERRUPTED. HOWEVER, IN THE UNLIKELY EVENT OF AN INTERRUPTION IN SERVICES, WE SHALL NOT BE LIABLE OR RESPONSIBLE FOR ANY LOSS OR DAMAGE, HOWSOEVER CAUSED OR SUFFERED BY THE USER.</p>

<p class="text-justify"><strong>Third party rights</strong></p>

<p class="text-justify">Nothing in this Agreement is intended to nor shall confer a benefit on any third party and any person who is not a party to this Agreement has no rights to enforce them.</p>

<p class="text-justify"><strong>Waiver</strong></p>

<p class="text-justify">No delay or decision not to enforce rights under this Agreement will constitute a waiver of the right to do so and will not affect rights in relation to any subsequent breach. If You encounter any error while viewing any file/ document, kindly notify us of the same at the earliest either by mail or phone.</p>



<p class="text-justify"><strong>Information Technology Act</strong></p>

<p class="text-justify">Certain laws in India prohibit and impose restriction on use of the Website and You are advised to make familiar with those laws and not to post any information or messages that are, or that may be construed, as being malicious, slanderous, pornographic, defamatory, inappropriate or that makes attacks on or comments on any individuals or groups of individuals, educational institutions or any other entities whatsoever (whether companies, firms, or any other institutions).&nbsp;</p>

<p class="text-justify">You also agree to not post any information to which You do not have copyright and/or other appropriate permissions to post in public forum.</p>

<p class="text-justify">Your failure to comply with these terms may result in removal of Your postings without prior notice as a User. The IP address of all posts is recorded to aid in enforcing these conditions.</p>

<p class="text-justify"><strong>Other Laws</strong></p>

<p class="text-justify">Certain laws require companies to maintain data with respect to goods and services and other personal information in a prescribed format and Nyx Wolves will use all the information to the extent required in compliance with the applicable laws and as may be directed or amended from time to time.</p>

<p class="text-justify"><strong>Force Majeure</strong></p>

<p class="text-justify">Nyx Wolves shall not be liable and to the extent, that the performance or delay in performance of any of its obligations are prevented, restricted, delayed or interfered with due to circumstances beyond the reasonable control and without the fault or negligence of such Party, including but not limited to change in legislation, fire, flood, explosion, epidemic, pandemic including COVID19, plague, accident, act of god, war, riot, strike, lockout, traffic or other concerted act of workmen and/or act of Government.</p>

<p class="text-justify"><strong>Headings</strong></p>

<p class="text-justify">The headings and subheadings herein are included for convenience and identification only and are not intended to describe, interpret, define or limit the scope, extent or intent of this Agreement contained herein or any other section or pages of the Website or any Linked Sites in any manner whatsoever.</p>

<p class="text-justify"><strong>Purchase Policy</strong><br />
Nyx Wolves accepts payment methods as displayed through the Website from time to time. It shall be Nyx Wolves&rsquo; sole discretion to change the acceptable payment methods.</p>

<p class="text-justify"><strong>Governing Law and Jurisdiction</strong></p>

<p class="text-justify">This Agreement is governed by the laws of India. Any disputes arising out of or in connection with these terms and conditions shall be resolved by a sole arbitrator appointed mutually by the parties concerned, in accordance with the Indian Arbitration and Conciliation Act, 1996. The arbitration proceedings shall be in the English language. The seat and venue of arbitration shall be Chennai, Tamilnadu.</p>

<p class="text-justify"><strong>Acceptance of Terms and Conditions</strong></p>

<p class="text-justify">By using our Website, You agree to be bound by these terms and conditions and privacy policy set forth below including any additions and future modifications. If at any time You do not agree to these terms and conditions, You may notify us of Your intention and refrain from accessing our Website.</p>

            </div>
        </div>
    </div>
</section>
@endsection